server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone=http://peer1:8761/eureka/
spring:
  application:
    name: simple-service
 
#spring.cloud.config.name=config
#spring.cloud.config.profile=${config.profile:dev}
#spring.cloud.config.uri=http://127.0.0.1:${config.port:8888}